use_frameworks!


source 'https://github.com/iOSModularization/AHFMSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'



target 'AHFMHistoryVCServices_Example' do
  pod 'AHFMHistoryVCServices', :path => '../'

  target 'AHFMHistoryVCServices_Tests' do
    inherit! :search_paths

    
  end
end
